A = (10, 20, 30)
B = (1, 2, 3)
C = (3,)
D = ()
E = ()
F = (3,)
G = ('John', 27)

print("tuple A: " + str(A))
print("tuple B: " + str(B))
print("tuple C: " + str(C))
print("tuple D: " + str(D))
print("tuple E: " + str(E))
print("tuple F: " + str(F))
print("tuple G: " + str(G))